---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: broadinstitute/puppet-gcloudsdk
  description:
    "Puppet module to download, install, and configure the gcloud SDK"
  name: puppet-gcloudsdk
  tags:
    - bits
    - bits-tools
    - gcloud
    - puppet
  title: puppet-gcloudsdk
spec:
  lifecycle: production
  owner: bits-aviso
  system: puppet
  type: service
